change order of checks (tsc -> lint -> prettier)

diff --git a/huskyhooks/pre-merge-commit b/huskyhooks/pre-merge-commit
--- a/huskyhooks/pre-merge-commit
+++ b/huskyhooks/pre-merge-commit
@@ -11,22 +11,22 @@ if [ $tscStatus -ne 0 ]; then
     exit 1
 fi
 
-npx prettier . --check
-pretStatus=$?
+npx next lint
+lintStatus=$?
 
-if [ $pretStatus -ne 0 ]; then
-    echo "Files do not align with Pretter code convention."
-    echo "Please run 'npm run pret:fix' before merging the commit."
+if [ $lintStatus -ne 0 ]; then
+    echo "Linting has failed."
+    echo "Please fix the errors before merging the commit."
     exit 1
 fi
 
-npx next lint
-lintStatus=$?
+npx prettier . --check
+pretStatus=$?
 
 if [ $tscStatus -eq 0 ] && [ $pretStatus -eq 0 ] && [ $lintStatus -eq 0 ]; then
     exit 0
 else
-    echo "Linting has failed."
-    echo "Please fix the errors before merging the commit."
+    echo "Files do not align with Pretter code convention."
+    echo "Please run 'npm run pret:fix' before merging the commit."
     exit 1
 fi
